services:
  database:
    image: postgres:17
    restart: always #unless-stopped # change to always when in production
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file: ".env"

  django:
    build: ./evergreen
    ports:
      - '8080:8080'
    env_file: ".env"
    volumes:
    - ./media:/root/media
    depends_on:
      - database 

  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./evergreen/staticfiles:/static
      - ./media:/media
