services:
  database:
    image: postgres:17
    restart: always
    shm_size: 128mb
    env_file: ".env"

  django:
    build: ./evergreen
    restart: always
    env_file: ".env"
    volumes:
    - ./media:/root/media
    depends_on:
      - database

  nginx:
    build: ./nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - ./evergreen/staticfiles:/static
      - ./media:/media
    depends_on:
      - django
