server {
    
    server_name localhost;
    listen 443 ssl;
    
    ssl_certificate /etc/nginx/cert.pem;
    ssl_certificate_key /etc/nginx/private.key; ###need to get key --> check vid for code

    location / {
        proxy_pass http://localhost:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    location ~ \.(gif|jpg|png|mp4)$ {
        root /media/image_upload;
    }

}

server {

    server_name localhost;
    listen 80;

    listen / {

        return 301 https://localhost$request_uri;

    }

}