# Generated by Django 5.1.2 on 2024-10-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eg_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
