# load_module modules/ngx_http_js_module.so;
# js_import rate_limit.js;

# Rate limiting for demo
# See: https://blog.nginx.org/blog/rate-limiting-nginx
# See: https://blog.nginx.org/blog/mitigating-ddos-attacks-with-nginx-and-nginx-plus

# Allowlisted IPs -- insert demo IP here
geo $limit {
    default 1;
    10.0.0.0/8 0;
    192.168.0.0/24 0;
    174.208.43.71/24 0; # demo ip
}

# Determines if allowlist is hit or not
map $limit $limit_key {
    0 "";
    1 $binary_remote_addr;
}
map $limit $limit_key_global {
    0 "";
    1 1;
}

# Sets up per-IP rate limit (w/ allowlist)
limit_req_zone $limit_key zone=req:10m rate=10r/s;
limit_req_status 429;

# Sets up global IP rate limit (w/ allowlist)
limit_req_zone $limit_key_global zone=req_global:10m rate=500r/s;

# Sets up limit for active connections from one IP
limit_conn_zone $limit_key zone=conn:10m;
limit_conn_status 429;

# Lower timeout for clients sending data too slowly
# (i think this was only 365 but pulling out all the stops here)
client_body_timeout 5s;
client_header_timeout 5s;

server {
    # js_content rate_limit.check;

    server_name localhost;
    listen 443 ssl;
    
    ssl_certificate /etc/nginx/cert.pem;
    ssl_certificate_key /etc/nginx/private.key;


    location /relay-upload {
        client_max_body_size 50M;
        proxy_pass http://django:8080/relay-upload;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    # Enables rate limits for this connection

    # Allow burst of 20 req, allow 5 before delay
    # (see https://blog.nginx.org/blog/rate-limiting-nginx)
    limit_req zone=req burst=20 delay=5;
    # Allow burst of 500 req globally with no delay
    limit_req zone=req_global burst=500 nodelay;
    # No more than 20 active connections per IP
    limit_conn conn 20;


    location /static/ {
        root /;
    }

    location /media/image_upload/ {
        root /;
    }

    location / {
        proxy_pass http://django:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}

# Upgrade insecure connections to HTTPS
server {
    # js_content rate_limit.check;
    client_max_body_size size;

    server_name localhost;
    listen 80;
    listen 8080;

    location / {
        return 301 https://$host$request_uri;
    }
}
